---
galaxy_info:
  author: Portail Securise Team
  description: Deploy Credentials API for secure password storage
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: common
