$ANSIBLE_VAULT;1.1;AES256
66626231633162353038343037383762393437373461323730616334306239333635343765346363
6332316133316337326334353162386232386465303739360a366634353734343933313230626136
36646533626261353538383233386137326163653865393966313834313838316539323664626161
3861656538383435370a343636333565386130353030363965613932623864623266633963613864
32313364393764353439396632323133653138363861613163323532363766386664643033383036
37313734373064643038633038636265366161383261636137663765313634616263346635313137
37643233373936346436383534363666653662303539646565366161643331386236393364353335
66643064323934353137383831613731393538323337663566653432616632323836663563663730
63623433313536393336333230663434616335646135666337623664623232353231613233336533
61316439633430343630386135386465376337366430646665366134613061396663633938313031
62323863373862303566353932376135643237626233313731393265363664366130353933343332
34663635393837353438316533626261336539313366633034386235623137353333333832326437
31646562646362333338353436626136623436373137653636666431313864396430343539376435
33376436373031303365376561343465666265616138616663313263323964366565653562383663
62666436366432383936383236396635306231306563636539323631313335303533303533653563
34346632626530336135623238346364646132326133386136376138656331346339663662393830
31363966643234353937656536633566623030383231313434333166643735366238
