---
# =============================================================================
# luks â€” Install
# =============================================================================

- name: Install cryptsetup
  ansible.builtin.apt:
    name: cryptsetup
    state: present
    update_cache: true
    cache_valid_time: 3600
