---
# =============================================================================
# wireguard role defaults
# =============================================================================

# -- Interface ----------------------------------------------------------------

wg_interface: wg0
wg_address: ""
wg_listen_port: ""
wg_private_key: ""

# -- Peer ---------------------------------------------------------------------

wg_peer_public_key: ""
wg_peer_endpoint: ""
wg_peer_allowed_ips: ""
wg_persistent_keepalive: ""

# -- Firewall rules (optional) -----------------------------------------------

wg_post_up: ""
wg_post_down: ""

# -- State --------------------------------------------------------------------

wg_state: present
wg_enabled: true
